[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TPO_2"
version = "0.1.0"
description = "..."
authors = [
    { name = "...", email = "your.email@example.com" }
]
dependencies = [
    "pytest",
]